### ISSUE TITLE
 Version in "./docker-compose.yml" is unsupported (Ubuntu 18.10)

### ISSUE THREAD

**Issue by programmieraffe** [sroertgen/oerhoernchen20_docker#4]
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1. For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

docker-compose --version:
docker-compose version 1.21.0, build unknown

grep version docker-compose.yml
version: "3.7"

I solved the issue via https://github.com/10up/wp-local-docker/issues/58#issuecomment-476786006 and updated the package manually to 1.25.4

`sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose` 

but maybe backwards compatibility for older OS would be good?

**Comment by sroertgen** [comment]
Yes, definitely. I don't think I'm using any too recent features of docker-compose, so it should be possible. I will check.

**Comment by sroertgen** [comment]
downgraded compose-file version to 3.
